name: RTVFX Blog
favicon: null
layout_spectrum: 0.8574587835464627
typography_spectrum: 0.2920128491241485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.09114421368576586
  lightness: 0.4962938993703574
  saturation: 0.7712112353183329
  rhythmicContrast: 0.45352387032471597
purpose: []
